services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    volumes:
      - db_data:/app/db


  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
